---
title: 'Índice'
author: "Alejandro Yerovi"
date: "22/7/2021"
output: html_document
site: blogdown:::blogdown_site
---
<aside class="search-results" id="search">

<div class="container">

<section class="search-header">

<div class="row no-gutters justify-content-between mb-3">

<div class="col-6">

# Search

</div>

<div class="col-6 col-search-close">[](#)</div>

</div>

<div id="search-box"><input name="q" id="search-query" placeholder="Search..." autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" type="search"></div>

</section>

</div>

</aside>

<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">

<div class="container">

<div class="d-none d-lg-inline-flex">[Academic](/)</div>

<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"><span></span></button>

<div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">[Academic](/)</div>

<div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

*   [<span>Demo</span>](/#hero)
*   [<span>Posts</span>](/#posts)
*   [<span>Projects</span>](/#projects)
*   [<span>Publications</span>](/#featured)
*   [<span>Courses</span>](/courses/)
*   [<span>Contact</span>](/#contact)

</div>

*   [](#)
*   [](#)

    <div class="dropdown-menu">[<span>Light</span>](#) [<span>Dark</span>](#) [<span>Automatic</span>](#)</div>

</div>

</nav>

<div class="universal-wrapper pt-3">

# Page not found

<form class="d-flex align-items-center mb-3"><input name="q" type="search" class="form-control" placeholder="Search..." autocomplete="off"></form>

Perhaps you were looking for one of these?

## Latest

*   [Primer Post](/post/2020-12-01-r-rmarkdown/)
*   [Example Page 2](/courses/example/example2/)
*   [Example Talk](/talk/example/)
*   [Almost Done](/post/almost-done/)
*   [Test Post](/post/test-post/)
*   [Test RMD File](/post/test-rmd-file/)
*   [Writing technical content in Academic](/post/writing-technical-content/)
*   [An example preprint / working paper](/publication/preprint/)
*   [Display Jupyter Notebooks with Academic](/post/jupyter/)
*   [Slides](/slides/example/)

</div>

<script>const code_highlighting = true;</script> <script>const isSiteThemeDark = false;</script> <script>const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3}; const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"}; const content_type = { 'post': "Posts", 'project': "Projects", 'publication' : "Publications", 'talk' : "Talks", 'slides' : "Slides" };</script> <script id="search-hit-fuse-template" type="text/x-template"><div class="search-hit" id="summary-{{key}}"> <div class="search-hit-content"> <div class="search-hit-name"> <a href="{{relpermalink}}">{{title}}</a> <div class="article-metadata search-hit-type">{{type}}</div> <p class="search-hit-description">{{snippet}}</p> </div> </div> </div></script>

<div class="container">

<footer class="site-footer">

Powered by the [Academic theme](https://sourcethemes.com/academic/) for [Hugo](https://gohugo.io).<span class="float-right" aria-hidden="true">[<span class="button_icon"></span>](#)</span>

</footer>

</div>

<div id="modal" class="modal fade" role="dialog">

<div class="modal-dialog">

<div class="modal-content">

<div class="modal-header">

##### Cite

<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>

<div class="modal-footer">[Copy](#) [Download](#)</div>

</div>

</div>

</div>