---
title: "Mi Primer Post de R-Markdown"
author: "Alejandro Yerovi"
date: "`r format(Sys.time(), '%d %B, %Y')`"
categories: ["R"]
tags: ["R-Markdown", "Blogdown", "Web Site"]
params:
  code: False
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$code)
```

# R Markdown

R Markdown es una poderosa herramienta que no sólo permite crear documentos sino también muchos otros proyectos como libros y páginas web.

Se puede poner código de R:

```{r cars}
summary(cars)
fit <- lm(dist ~ speed, data = cars)
fit
```

# Incluir Gráficos

Se pueden poner gráficos de R en la página web. Mire la figura \@ref(fig:pie) por ejemplo:

```{r pie, fig.cap='Un gráfico Llamativo.', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Cielo', 'Lado Soleado de la Pirámide', 'Lado con Sombra de la Pirámide'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

Y otro gráfico:
```{r echo=FALSE}
library(ggplot2)
ggplot(Orange, aes(x = age, 
                   y = circumference, 
                   color = Tree)) +
  geom_point() +
  geom_line() +
  guides(color = FALSE) +
  theme_bw()
```

Y ahora un poco de Plotly:

```{r}
library(plotly)

fig <- plot_ly(
    domain = list(x = c(0, 1), y = c(0, 1)),
    value = 270,
    title = list(text = "Speed"),
    type = "indicator",
    mode = "gauge+number") 
fig <- fig %>%
  layout(margin = list(l=20,r=30))

fig
```
